### ISSUE TITLE
[Linux] cli.py results to service unavailable

### ISSUE THREAD

**Issue by Nebdir** [Advik-B/CMPDL#14]
## reproduce

1. download git repo
2. create python venv
3. install requirements
4. run cli normaly with options to file.zip and output

## logs
[log.txt](https://github.com/Advik-B/CMPDL/files/9131528/log.txt)

## expected behaviour
downloading modpack to directory

**Comment by KorewaLidesu** [comment]
Check this issue for reference
As Curse trash the old API away, meaning that this project will not working anymore
~~although alternative solution do exist, just have wait for update~~
https://github.com/Owen-Cochell/cursepy/issues/8

**Comment by Advik-B** [comment]
This is not an error with CMPDL but cursepy. It has something to do with the curseforge API

**Comment by Advik-B** [comment]
The best bet is to wait it out. I myself cannot do anything unless:
- cursepy gets a revamp
- Curseforge API is back up again
- The **NEW** Curseforge API is finished

**Comment by Advik-B** [comment]
Sorry. but all I can do is wait
I have exams now. I will look into it in a week. Next Sunday maybe?

**Comment by Advik-B** [comment]
@Hero9909 can you please upload the logs. A folder will be created called `logs`, upload all the files you find in there
<img width="92" alt="Screenshot 2022-07-22 at 9 11 42 AM" src="https://user-images.githubusercontent.com/86160411/180357870-4add3130-fd44-4069-bbe5-2016949d068d.png">

**Comment by KorewaLidesu** [comment]
@Advik-B can you help me compile this? cant compile it myself ;;;;;;;;;
https://github.com/KorewaLidesu/CMPDL

**Comment by Advik-B** [comment]
ok

**Comment by Advik-B** [comment]
Do not use cx_Freeze for linux or mac.

**Comment by KorewaLidesu** [comment]
Sorry, should have try Window first ;;;;;;;

**Comment by Advik-B** [comment]
sure, `Advik#9471` is my discord. if you need any help, dm me

**Comment by Advik-B** [comment]
Closing in favor of the latest patch: [v2.5.5](https://github.com/Advik-B/CMPDL/releases/tag/v2.5.5)
