### ISSUE TITLE
[BUG] CurseAPI has been revamp

### ISSUE THREAD

**Issue by KorewaLidesu** [Advik-B/CMPDL#15]
Curse has changed their API system mean CursePy no longer work
As the solution for now is to implement API direct or wait for update from CursePy
Example: https://github.com/PolyMC/PolyMC/tree/develop/launcher/modplatform/flame

**Comment by Advik-B** [comment]
F

**Comment by Advik-B** [comment]
Will work on it

**Comment by Advik-B** [comment]
Sorry. but all I can do is wait
I have exams now. I will look into it in a week. Next Sunday maybe?

**Comment by Advik-B** [comment]
see #14

**Comment by Advik-B** [comment]
Why did you close it?

**Comment by KorewaLidesu** [comment]
> Why did you close it?

Closed this as issue should be resolved.
~~Oh, I forget that it still on progress :killme:~~
