### ISSUE TITLE
More Bugs - Need fixes

### ISSUE THREAD

**Issue by KorewaLidesu** [Advik-B/CMPDL#17]
[First one](https://github.com/Advik-B/CMPDL/blob/f60550366c2222112195bcaab58a086e3064ad40/src/backend.py#L31) dont close on itself -> cause non Indented block
[This one](https://github.com/Advik-B/CMPDL/blob/f60550366c2222112195bcaab58a086e3064ad40/src/__main__.py#L87) not work because there isnt `connect` property avail

Also cursepy is updated, you can use new API now without changing code ~~and close https://github.com/Advik-B/CMPDL/pull/16 as its no longer needed~~

**Comment by Advik-B** [comment]
Should fix the first one

**Comment by Advik-B** [comment]
Will work on this ASAP

**Comment by Advik-B** [comment]
f37cadd4a06d85dbe3b1f93ab64b766e9d915899 should fix some of them. But it is very unstable

**Comment by Advik-B** [comment]
[v2.0.0](https://github.com/Advik-B/CMPDL/releases/tag/v2.0.0) Should be stable (cli text is the stable one)
