### ISSUE TITLE
Cursepy cannot download the correct version of the mod if we use guess_download()

### ISSUE THREAD

**Issue by ArcadeArchie** [Advik-B/CMPDL#32]
As mentioned #25 when we need to use curspy's `guess_download()` it sometimes incorrectly downloads the mod file.

i haven't been able yet to figure out what causes the incorrect download.

**Comment by ArcadeArchie** [comment]
this is just some 5min research i did but instead of using `guess_download` we can build the download url our self since the url seems fairly deterministic `https://www.curseforge.com/minecraft/mc-mods/{modName}/download/{fileId}/file`

**Comment by Advik-B** [comment]
> this is just some 5min research i did but instead of using `guess_download` we build the download url ourself since the url seems fairly deterministic `https://www.curseforge.com/minecraft/mc-mods/{modName}/download/{fileId}/file` 

Yea, I used to do that before using cursepy

**Comment by ArcadeArchie** [comment]
since we got the necessary data in the CurseFile instance it should be trivial to implement

**Comment by Advik-B** [comment]
Hovever, you need to bypass cloudflare ant-bot system to download it

**Comment by Advik-B** [comment]
I will try to use my version of the curseforge wrapper and see if that helps

**Comment by ArcadeArchie** [comment]
ok

**Comment by ArcadeArchie** [comment]
should be easier to use since the `v1/mods/files` endpoint takes a number array of the file Ids we want and returns a `downloadUrl`

**Comment by Advik-B** [comment]
Yea, ill be using this:

[get-mod-file-download-url](https://docs.curseforge.com/#get-mod-file-download-url)

---

[My implementation of curseforge](https://github.com/Advik-B/curseforge-api)

**Comment by ArcadeArchie** [comment]
question now is what about the required API Key?

**Comment by Advik-B** [comment]
My api key is public, it is in `v.py`

**Comment by Advik-B** [comment]
I am trusting the community not to misuse the API key

**Comment by ArcadeArchie** [comment]
you should probably not publish your own API key

**Comment by ArcadeArchie** [comment]
> Yea, ill be using this:
> 
> [get-mod-file-download-url](https://docs.curseforge.com/#get-mod-file-download-url)
> 
> [My implementation of curseforge](https://github.com/Advik-B/curseforge-api)

i recommend to use this one instead [files-get-files](https://docs.curseforge.com/#get-files) since we can get all URLs in bulk and do less requests

**Comment by Advik-B** [comment]
Aah, thats a good idea. ill add your name to the contributor list..

**Comment by ArcadeArchie** [comment]
may sound like a shameless plug but i have my own downloader which is implemented in C# so idk how much help its gonna be
[CurseForgeManifestService](https://github.com/ArcadeArchie/CurseForgeDownloader/blob/e3bc7e94279f41f0af7e78e2f5b7b3f5414e341f/CurseForgeDownloader/Services/CurseForgeManifestService.cs#L41)

**Comment by Advik-B** [comment]
Yea, I saw your repo, I was checking out your profile

**Comment by ArcadeArchie** [comment]
So i found this out just now while testing my own downloader and sometimes the API returns null for the downloadUrl on certain mods i.e.
![image](https://user-images.githubusercontent.com/29282748/204651431-5fb7608e-87de-436f-a4d4-cf3f4f9300cc.png)

**Comment by ArcadeArchie** [comment]
as a workaround i manually guess the download link that the API would return
![image](https://user-images.githubusercontent.com/29282748/204651742-64911782-2ddd-4345-9aba-fc9bc8c31ef7.png)

**Comment by ArcadeArchie** [comment]
also with mods that have a null downloadUrl [get-mod-file-download-url](https://docs.curseforge.com/#get-mod-file-download-url) returns a 403

**Comment by Advik-B** [comment]
On 5/12/2022 I will work on this. My exams are going on

**Comment by Advik-B** [comment]
@ArcadeArchie check 46ad21089824569915fc376abf618db96acffdad, I started using my own curseforge wrapper
Just wanted to let you know, I had free time to study IT but I spent it on this. GTG I have to study

**Comment by Advik-B** [comment]
@ArcadeArchie please wait a while. I am on a break until new year

**Comment by Advik-B** [comment]
My rewrite is dope (without cache)
<img width="308" alt="Screenshot 2022-12-28 at 11 00 29 PM" src="https://user-images.githubusercontent.com/86160411/209850428-d570d16a-d048-4deb-bd39-816b919a82a8.png">

(With cache)
<img width="312" alt="Screenshot 2022-12-28 at 11 05 15 PM" src="https://user-images.githubusercontent.com/86160411/209850762-b68e1858-6260-49e4-80e1-5751ffd512e5.png">

The modpack is `sample.manifest.json`

**Comment by Advik-B** [comment]
This includes guessing, and sending the request

**Comment by Advik-B** [comment]
All the mods 7 (without cache) (Over 100+ mods)
<img width="334" alt="Screenshot 2022-12-28 at 11 19 55 PM" src="https://user-images.githubusercontent.com/86160411/209852485-fc62da7e-24d5-4325-ab63-55633f55f873.png">

With cache: [Black Adam In The Background]
<img width="313" alt="Screenshot 2022-12-28 at 11 37 29 PM" src="https://user-images.githubusercontent.com/86160411/209854421-2719503d-45f3-49d4-b074-310225ada74e.png">

**Comment by ArcadeArchie** [comment]
noice

**Comment by Advik-B** [comment]
Happy New Year Btw

**Comment by Advik-B** [comment]
Please give [v3.0.0](https://github.com/Advik-B/CMPDL/releases/tag/v3.0.0) a try, I risked failing my exams to do this lol

**Comment by ArcadeArchie** [comment]
runs pretty nicely havent had any issues with downloading so far.
so i guess we can close this now?

**Comment by Advik-B** [comment]
Ok, but... does it run faster than ever?
PS: I failed my math & science 😔

**Comment by ArcadeArchie** [comment]
varies, so i would need to some more thorough testing but it felt notably faster
PS: my condolences, gl next time

**Comment by Advik-B** [comment]
Thanks, GL;HF
