### ISSUE TITLE
Add CLI support

### ISSUE THREAD

**Issue by juraj-hrivnak** [Advik-B/CMPDL#4]
I just found your tool, and it looks really promising. CLI support is like a must-have :P

**Comment by Advik-B** [comment]
Ok!, I am glad someone found this. the program used to have CLI support in [v1.0.0-alpha](https://github.com/Advik-B/CMPDL/tree/v1.0.0-alpha) but I removed it.
Thank you for asking. I will put CLI support back! in v1.5.0
Thank you for noticing my project. I was on the verge of abandoning it. You made my day!

NOTE: Do **NOT** use [v1.0.0-alpha](https://github.com/Advik-B/CMPDL/tree/v1.0.0-alpha) as it is very unstable and it uses an old method of getting the mod (which can almost KILL your internet speed).

**Comment by Advik-B** [comment]
ALMOST DONE!

**Comment by juraj-hrivnak** [comment]
Nice, thank you for focusing on this project!

**Comment by Advik-B** [comment]
DONE, I will release the build today, let me know if there are any bugs
ALSO: Sorry for the delay man :-( 
I had a LOT of stuff going on, also I had EXAMS.
Thanks for the patience

**Comment by Advik-B** [comment]
[v1.5.0](https://github.com/Advik-B/CMPDL/releases/tag/v1.5.0) the you go! @juraj-hrivnak

**Comment by juraj-hrivnak** [comment]
Thank you so much! I appreciate it, it was actually really quick, everyone has exams at this time.
I will test it like exactly now!

**Comment by juraj-hrivnak** [comment]
Just tested it, and it works like a charm!
